// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Amar(arg1:string,arg2:string):Promise<string>;

export function GenerarRandomPercent(arg1:number,arg2:number):Promise<string>;

export function Greet(arg1:string):Promise<string>;

export function Sum(arg1:string,arg2:string):Promise<string>;
