// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function Amar(arg1, arg2) {
  return window['go']['main']['App']['Amar'](arg1, arg2);
}

export function GenerarRandomPercent(arg1, arg2) {
  return window['go']['main']['App']['GenerarRandomPercent'](arg1, arg2);
}

export function Greet(arg1) {
  return window['go']['main']['App']['Greet'](arg1);
}

export function Sum(arg1, arg2) {
  return window['go']['main']['App']['Sum'](arg1, arg2);
}
