name: Build and Release

on:
  push:
    branches: [ main ]

jobs:
  build:
    name: Build and Release
    runs-on: windows-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        
      - name: Setup Go
        uses: actions/setup-go@v4
        with:
          go-version: '1.21'
          
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          
      - name: Install Wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest
          
      - name: Create required directories and files
        run: |
          mkdir -p build
          # Creating a simple icon file to satisfy the build requirement
          curl -o build/appicon.png https://wails.io/img/logo-universal.png
          
      - name: Build project with Wails
        run: wails build -f -o build/app.exe
          
      - name: Create Release
        id: create_release
        uses: softprops/action-gh-release@v1
        with:
          files: build/app.exe
          name: Release ${{ github.sha }}
          tag_name: v${{ github.run_number }}
          body: |
            Automated release for commit ${{ github.sha }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}