name: Release Build

on:
  push:
    branches:
      - main
    tags:
      - 'v*.*.*'

jobs:
  build:
    strategy:
      matrix:
        os: [windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Go
      uses: actions/setup-go@v4
      with:
        go-version: '1.21'

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'
        cache: 'pnpm'

    - name: Install pnpm
      run: npm install -g pnpm

    - name: Install dependencies
      working-directory: frontend
      run: pnpm install

    - name: Build project
      run: |
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          bash scripts/build-windows.sh
        else
          bash scripts/build-macos.sh
        fi

    - name: Zip binaries
      run: |
        cd bin
        if [[ "${{ matrix.os }}" == "windows-latest" ]]; then
          zip -r LoveCalc-Windows-${{ github.sha }}.zip *.exe
        else
          zip -r LoveCalc-MacOS-${{ github.sha }}.zip *.app
        fi

    - name: Upload artifacts
      uses: actions/upload-artifact@v4
      with:
        name: binaries-${{ matrix.os }}
        path: bin/*.zip

  create-release:
    needs: build
    if: startsWith(github.ref, 'refs/tags/')
    runs-on: ubuntu-latest
    steps:
    - name: Download artifacts
      uses: actions/download-artifact@v4
      with:
        path: artifacts

    - name: Create Release
      uses: softprops/action-gh-release@v1
      with:
        tag_name: ${{ github.ref }}
        name: LoveCalc ${{ github.ref_name }}
        body: |
          ## Changes
          - Built from ${{ github.sha }}
          - Automated release generated on ${{ github.event.head_commit.timestamp }}
          - Includes Windows and macOS builds
        files: |
          artifacts/**/*.zip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
